services:

  postgres:
    image: postgres:16
    restart: always

    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: api_cursos

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d api_cursos"]
      interval: 5s
      timeout: 5s
      retries: 10


  api:
    build: .
    restart: always

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/api_cursos
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    ports:
      - "8080:8080"


volumes:
  postgres_data: